---

- hosts: all
  become: true
  tasks:

  - name: install HTTP package
    package:
      name: 
        - "{{ web_package }}"
        - "{{ python_package }}"
      state: latest
      update_cache: true

  - name: Start and enable httpd service
    service:
      name: httpd
      state: started
      enabled: true 
    when: ansible_distribution in ["Rocky","CentOS"]
