---

- hosts: all
  become: true
  tasks:

  - name: Updating Repo Index
    yum:
      update_cache: yes 
    when: ansible_distribution in ["Rocky","CentOS"]

  - name: install HTTP package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution in ["Rocky","CentOS"]

  - name: Start and enable httpd service
    service:
      name: httpd
      state: started
      enabled: true 
    when: ansible_distribution in ["Rocky","CentOS"]

  - name: Updating Repo Index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu","Debian"]

  - name: install HTTP package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Ubuntu","Debian"]


