---

- hosts: all
  become: true
  tasks:

  - name: Updating Repo Index
    yum:
      update_cache: yes 

  - name: install HTTP package
    yum:
      name: httpd
      state: latest

  - name: Start and enable httpd service
    service:
      name: httpd
      state: started
      enabled: true 
